#!/bin/bash 

# test-file: tests if a file exists or not ..

FILE=~/.bashrc


# main program block 
if [ -e "$FILE" ]; then
      if [ -f "$FILE"  ]; then
	  echo "file: $FILE is a regular file "
      fi
	if [ -d "$FILE" ]; then
		echo "$FILE is directory!"
     	fi 
	if [ -r "$FILE" ]; then
		echo "$FILE  is readable"
	fi
	if [ -w "$FILE" ]; then
		echo "$FILE is writable"
	fi
	if [ -x "$FILE" ]; then
		echo "$FILE is executable"
	fi

  else
	  echo "$FILE does not exist!"
	  exit 1
  fi

exit	##<--- the return status without arguments take
	# the exit status from the last expressoin or command
