#!/bin/bash - 

## shell function skell
## SHell function definitions must appear in the script 
## before ther are called 

function step2 {
	echo "Step 2"
	return
}

### main block starts here
echo "step 1"
step2 # <------ function Call
echo "step 3"
